### ISSUE TITLE
Change the "Create A Transfer" button on the transfer page to a dropdown

### ISSUE THREAD

**Issue by aquabu** [CoMakery/comakery-server#1787]
# Goal

The goal of this task is to reorganize transfer page functionality to allow for new methods of creating a transaction - most notably for creating token vesting schedules. These new transfer methods will be added to the dropdown list as we develop them in follow on stories.

# Overview

### We are converting from these two buttons that opens the transfer form

<img width="1281" alt="Screen Shot 2020-12-29 at 11 00 24 PM" src="https://user-images.githubusercontent.com/7595/103335408-b3778080-4a29-11eb-991c-e92026045cb8.png">

### To a dropdown menu that opens the transfer form from these menu items:

<img width="236" alt="Screen Shot 2020-12-29 at 11 17 04 PM" src="https://user-images.githubusercontent.com/7595/103336154-10743600-4a2c-11eb-9844-29fed6101d2a.png">

Note that this is not pixel perfect. Use the existing styling for the page and site. For now, the "Create New Transfer" dropdown should appear where the current "Create a Transfer" is located.

# Tasks

- [ ] Rename "Create A Transfer" button to "Create New Transfer"
- [ ] Change that button to be the "Create New Transfer" dropdown menu
- [ ] Delete the Manage Types button because the functionality will move to the dropdown
- [ ] Add the "Manage Categories"  menu item that links to the "Manage Types" page
- [ ] Rename "Transfer Types" everywhere it's found in the app to "Transfer Categories"
- [ ] Rename the route `/projects/:id/dashboard/transfer_types` to `/projects/:id/dashboard/transfer_categories`
- [ ] When Burn, Mint, Bought or Earned are selected in the dropdown it should open the existing create transfer form with the type field automatically set to Burn, Mint, Bought or Earned
- [ ] Rename the Type field to "Category"

## Gherkin Style Scenario For RSpec Test
_(we aren't using cucumber but this is a good way to specify the behavior)_

GIven I am a project admin viewing the transfer page
When I click on the "Create A Transfer" menu
And I click the Burn menu item
Then the transfer form should open with the Burn category selected

(repeat that for Burn, Mint, Bought, Earned menu items)

GIven I am a project admin viewing the transfer page
When I click on the "Create A Transfer" menu
And I click the "Manage Categories" menu item
Then I should see the "Transfer Categories" page for the project
